name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release
    - name: Pack
      if: github.event_name != 'pull_request'
      run: dotnet pack -c Release -o ./artifacts/NuGet
    - name: Artifacts
      if: github.event_name != 'pull_request' && matrix.os == 'windows-2019'
      uses: actions/upload-artifact@master
      with:
        name: NuGet
        path: ./artifacts/NuGet

  publish-windows:
    name: Publish windows-latest
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish -c Release -f netcoreapp3.1 -r win7-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.1-win7-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
        dotnet publish -c Release -f netcoreapp3.1 -r win7-x64 -o ./artifacts/AvaloniaDemo.Experimental-netcoreapp3.1-win7-x64 ./samples/AvaloniaDemo.Experimental/AvaloniaDemo.Experimental.csproj
        dotnet publish -c Release -f netcoreapp3.1 -r win7-x64 -o ./artifacts/AvaloniaDemo.Perspectives-netcoreapp3.1-win7-x64 ./samples/AvaloniaDemo.Perspectives/AvaloniaDemo.Perspectives.csproj
        dotnet publish -c Release -f netcoreapp3.1 -r win7-x64 -o ./artifacts/AvaloniaDemo.Static-netcoreapp3.1-win7-x64 ./samples/AvaloniaDemo.Static/AvaloniaDemo.Static.csproj
        dotnet publish -c Release -f netcoreapp3.1 -r win7-x64 -o ./artifacts/Notepad-netcoreapp3.1-win7-x64 ./samples/Notepad/Notepad.csproj
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.1-win7-x64
        path: ./artifacts/AvaloniaDemo-netcoreapp3.1-win7-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo.Experimental-netcoreapp3.1-win7-x64
        path: ./artifacts/AvaloniaDemo.Experimental-netcoreapp3.1-win7-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo.Perspectives-netcoreapp3.1-win7-x64
        path: ./artifacts/AvaloniaDemo.Perspectives-netcoreapp3.1-win7-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo.Static-netcoreapp3.1-win7-x64
        path: ./artifacts/AvaloniaDemo.Static-netcoreapp3.1-win7-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: Notepad-netcoreapp3.1-win7-x64
        path: ./artifacts/Notepad-netcoreapp3.1-win7-x64

  publish-ubuntu:
    name: Publish ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish -c Release -f netcoreapp3.1 -r debian.8-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.1-debian.8-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
        dotnet publish -c Release -f netcoreapp3.1 -r ubuntu.14.04-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.1-ubuntu.14.04-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.1-debian.8-x64
        path: ./artifacts/AvaloniaDemo-netcoreapp3.1-debian.8-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.1-ubuntu.14.04-x64
        path: ./artifacts/AvaloniaDemo-netcoreapp3.1-ubuntu.14.04-x64

  publish-macOS:
    name: Publish macOS-latest
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish
      if: github.event_name != 'pull_request'
      run: dotnet publish -c Release -f netcoreapp3.1 -r osx.10.12-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.1-osx.10.12-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.1-osx.10.12-x64
        path: ./artifacts/AvaloniaDemo-netcoreapp3.1-osx.10.12-x64
